name: Build Hostel Management System

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Executable Fat JAR with Maven
      run: mvn clean package -DskipTests

    - name: Upload Built Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HostelManagementSystem-JAR
        path: target/hostel-system.jar
